/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.tsx',
    './app/**/*.{js,jsx,ts,tsx}',
    './app/**/(*).{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './screens/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        foreground: '#1f2937',
        card: '#ffffff',
        'card-foreground': '#1f2937',
        popover: '#ffffff',
        'popover-foreground': '#1f2937',
        primary: '#293341',
        'primary-foreground': '#fcfdff',
        secondary: '#f5f7f8',
        'secondary-foreground': '#293341',
        muted: '#f5f7f8',
        'muted-foreground': '#637083',
        accent: '#f5f7f8',
        'accent-foreground': '#293341',
        destructive: '#dc2626',
        'destructive-foreground': '#fcfdff',
        border: '#e6eaed',
        input: '#e6eaed',
        ring: '#a8b0ba',
        success: '#059669',
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '10px',
        xl: '14px',
        '2xl': '18px',
        '3xl': '22px',
        '4xl': '26px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(15, 23, 42, 0.08)',
        sm: '0 4px 10px rgba(15, 23, 42, 0.08)',
      },
    },
  },
  plugins: [],
};
