/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './App.tsx',
    './app/**/*.{js,jsx,ts,tsx}',
    './app/**/(*).{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './screens/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        foreground: '#1f2937',
        card: '#ffffff',
        'card-foreground': '#1f2937',
        popover: '#ffffff',
        'popover-foreground': '#1f2937',
        primary: '#e62a2b',
        'primary-foreground': '#fff5f5',
        secondary: '#f8fafc',
        'secondary-foreground': '#1f2937',
        muted: '#f8fafc',
        'muted-foreground': '#64748b',
        accent: '#fff1f2',
        'accent-foreground': '#9f1239',
        destructive: '#dc2626',
        'destructive-foreground': '#fff5f5',
        border: '#e2e8f0',
        input: '#e2e8f0',
        ring: '#f87171',
        success: '#059669',
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '10px',
        xl: '14px',
        '2xl': '18px',
        '3xl': '22px',
        '4xl': '26px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(15, 23, 42, 0.08)',
        sm: '0 4px 10px rgba(15, 23, 42, 0.08)',
      },
    },
  },
  plugins: [],
};
